# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gaia < Formula
  desc "Token-trimmed CLI + MCP server for Forgejo and GitHub"
  homepage "https://github.com/stewartbrothers/gaia"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/stewartbrothers/gaia/releases/download/v0.4.0/gaia_v0.4.0_darwin_x86_64.tar.gz"
      sha256 "6bae5a1ecb262125b50aea31169ac1b22c792b0c9573e9302f418eb0b2e48108"

      def install
        bin.install "gaia"
        bin.install "gaia-mcp"
      end
    end
    on_arm do
      url "https://github.com/stewartbrothers/gaia/releases/download/v0.4.0/gaia_v0.4.0_darwin_arm64.tar.gz"
      sha256 "b724caa750f02012793092f410230816f491958d5c035deca38edd9e4ace972e"

      def install
        bin.install "gaia"
        bin.install "gaia-mcp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stewartbrothers/gaia/releases/download/v0.4.0/gaia_v0.4.0_linux_x86_64.tar.gz"
        sha256 "798915135f5f8abb8e7834d28eeaa4f4371e4a9354f06d362328cc98045758e4"

        def install
          bin.install "gaia"
          bin.install "gaia-mcp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stewartbrothers/gaia/releases/download/v0.4.0/gaia_v0.4.0_linux_arm64.tar.gz"
        sha256 "85035d2ff066139a28d9205916dde8ea998166755753abef0d582bdaeeb52824"

        def install
          bin.install "gaia"
          bin.install "gaia-mcp"
        end
      end
    end
  end

  test do
    system "#{bin}/gaia", "version"
  end
end
