# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gaia < Formula
  desc "Token-trimmed CLI + MCP server for Forgejo and GitHub"
  homepage "https://github.com/stewartbrothers/gaia"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/stewartbrothers/gaia/releases/download/v0.5.0/gaia_v0.5.0_darwin_x86_64.tar.gz"
      sha256 "4bab8c7ec1d85c863801fd26c0e2a17f352d135a5eafc479c092b7f969dcc7b6"

      def install
        bin.install "gaia"
        bin.install "gaia-mcp"
      end
    end
    on_arm do
      url "https://github.com/stewartbrothers/gaia/releases/download/v0.5.0/gaia_v0.5.0_darwin_arm64.tar.gz"
      sha256 "9131c3faf2e3e0975723deeb9495e5fe457e23cebc40c860ec9efec45c10db94"

      def install
        bin.install "gaia"
        bin.install "gaia-mcp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stewartbrothers/gaia/releases/download/v0.5.0/gaia_v0.5.0_linux_x86_64.tar.gz"
        sha256 "d69bcd301b5124565d1f47d58a07d6bd8221e0ef8b242832673d1cb63c72abdb"

        def install
          bin.install "gaia"
          bin.install "gaia-mcp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stewartbrothers/gaia/releases/download/v0.5.0/gaia_v0.5.0_linux_arm64.tar.gz"
        sha256 "decd462efddfb2c93bf78da866911a451deb93bd4b0524332b588e4694c58761"

        def install
          bin.install "gaia"
          bin.install "gaia-mcp"
        end
      end
    end
  end

  test do
    system "#{bin}/gaia", "version"
  end
end
