# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gaia < Formula
  desc "Token-trimmed CLI + MCP server for Forgejo and GitHub"
  homepage "https://github.com/stewartbrothers/gaia"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/stewartbrothers/gaia/releases/download/v0.4.1/gaia_v0.4.1_darwin_x86_64.tar.gz"
      sha256 "7e7874773b53a5388972e3c52613f6b13dddb1c4fcebe2762ef128dee1acbf61"

      def install
        bin.install "gaia"
        bin.install "gaia-mcp"
      end
    end
    on_arm do
      url "https://github.com/stewartbrothers/gaia/releases/download/v0.4.1/gaia_v0.4.1_darwin_arm64.tar.gz"
      sha256 "22cfcb8eadc268f331f6758acfc1467eee441aa5fb4e6d3933fe9bc02628a6a4"

      def install
        bin.install "gaia"
        bin.install "gaia-mcp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stewartbrothers/gaia/releases/download/v0.4.1/gaia_v0.4.1_linux_x86_64.tar.gz"
        sha256 "0e3437b2ff235beaa66036618720e51bba4c91296ecc1b9ea6f4742b247e798d"

        def install
          bin.install "gaia"
          bin.install "gaia-mcp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stewartbrothers/gaia/releases/download/v0.4.1/gaia_v0.4.1_linux_arm64.tar.gz"
        sha256 "216864700d154cf6675072a4e8da4c4f5d25454e5e58430165613c5f58cefa17"

        def install
          bin.install "gaia"
          bin.install "gaia-mcp"
        end
      end
    end
  end

  test do
    system "#{bin}/gaia", "version"
  end
end
